### PR TITLE
feature/errorHandler

### PR DESCRIPTION
**Pull request by gavin-brown**
## Error handling improvements
* On `400 Bad Request`, also send back the Caliper data that caused it.

### CODE REVIEW

**Comment by gavin-brown** [comment]
Testing comments!

**Comment by builtbywill** [comment]
@gavin-brown I think this should be merging into develop, not master, correct?

**Comment by gavin-brown** [comment]
Test comment!

**Comment by gavin-brown** [comment]
Test comment!

**Pull request merged**
